---
title: "Projects"
---

## Current Project

I am currently working on a project looking at situated predictors of hair pulling in individuals with trichotillomania (for more info on trichotillomania, click [here](http://www.bfrb.org/learn-about-bfrbs/trichotillomania)). This involves two studies, the first of which aims to generate norms of activities in which individuals with trichotillomania do or do not pull their hair in. 

The second will look at predictors of hair pulling, generating group and individual regression models, with the expectation that the individual level regression models will explain more of the variance than the group level ones.

##Previous Projects

As part of my final year project in my undergraduate degree, I conducted research under the supervision of [Miss Judith Stevenson](https://www.gla.ac.uk/schools/psychology/staff/judestevenson/). The research focused on correlations between shame, quality of life and symptom severity in individuals with body-focused repetitive behaviours (BFRBs), specifically trichotillomania and skin-picking disorder. we also investigated whether being "out" about one's BFRB would result in lower levels of shame. 

##Interesting Papers
If you would like to read more research about BFRBs I would recommend the follwing two as a starting point:

* Woods, D. W., Flessner, C. A., Franklin, M. E., Keuthen, N. J., Goodwin, R. D., Stein, D. J., & Walther, M. R. (2006). [The Trichotillomania impact project (TIP)](https://www.med.upenn.edu/ctsa/assets/user-content/documents/WoodsFranklin_TIP_2006.pdf). The Journal of Clinical Psychiatry, 67(12), 1877–1888. doi:10.4088/jcp.v67n1207

* Tucker, B. T. P., Woods, D. W., Flessner, C. A., Franklin, S. A., & Franklin, M. E. (2011). [The skin picking impact project: Phenomenology, interference, and treatment utilization of pathological skin picking in a population-based sample](http://www.sciencedirect.com/science/article/pii/S0887618510001714). Journal of Anxiety Disorders, 25(1), 88–95. doi:10.1016/j.janxdis.2010.08.007

